
import { PropertyData, PropertyFormData } from "@/types/property";

export interface PropertyTabContentsProps {
  activeTab: string;
  property: PropertyData;
  formState: PropertyFormData;
  agentInfo?: { id: string; name: string } | null;
  isUpdating?: boolean;
  isArchived?: boolean;
  onSave?: () => void;
  onDelete?: () => Promise<void>;
  handleSaveObjectId: (objectId: string) => Promise<void>;
  handleSaveAgent: (agentId: string) => Promise<void>;
  handleSaveTemplate: (templateId: string) => Promise<void>;
  handleGeneratePDF: () => void;
  handleWebView: (e: React.MouseEvent) => void;
  onFieldChange: (field: keyof PropertyFormData, value: any) => void;
  onAddFeature: () => void;
  onRemoveFeature: (id: string) => void;
  onUpdateFeature: (id: string, description: string) => void;
  onAddArea: () => void;
  onRemoveArea: (id: string) => void;
  onUpdateArea: (id: string, field: string, value: any) => void;
  onAreaImageRemove: (areaId: string, imageId: string) => void;
  onAreaImagesSelect: (areaId: string, imageIds: string[]) => void;
  onAreaImageUpload: (areaId: string, files: FileList) => Promise<void>;
  onFetchLocationData: () => Promise<void>;
  onGenerateLocationDescription: () => Promise<void>;
  onGenerateMap: () => Promise<void>;
  onRemoveNearbyPlace: (index: number) => void;
  isLoadingLocationData: boolean;
  isGeneratingMap: boolean;
  onFetchCategoryPlaces: (category: string) => Promise<any>;
  onFetchNearbyCities: () => Promise<void>;
  handleImageUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleRemoveImage: (index: number) => void;
  isUploading: boolean;
  handleAreaPhotosUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleRemoveAreaPhoto: (areaId: string, photoId: string) => void;
  handleFloorplanUpload: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleRemoveFloorplan: (index: number) => void;
  isUploadingFloorplan: boolean;
  handleSetFeaturedImage: (url: string | null) => void;
  handleToggleFeaturedImage: (url: string) => void;
  handleVirtualTourUpdate: (url: string) => void;
  handleYoutubeUrlUpdate: (url: string) => void;
  handleFloorplanEmbedScriptUpdate: (script: string) => void;
  currentStep: number;
  handleStepClick: (step: number) => void;
  onSubmit: () => void;
  setPendingChanges: (value: boolean) => void;
  isSaving?: boolean;
}

export interface TabContentRenderProps {
  activeTab: string;
  property: PropertyData;
  formState: PropertyFormData;
  agentInfo?: { id: string; name: string } | null;
  isUpdating?: boolean;
  isArchived?: boolean;
  handlers: {
    onSave?: () => void;
    onDelete?: () => Promise<void>;
    handleSaveObjectId: (objectId: string) => Promise<void>;
    handleSaveAgent: (agentId: string) => Promise<void>;
    handleSaveTemplate: (templateId: string) => Promise<void>;
    handleGeneratePDF: () => void;
    handleWebView: (e: React.MouseEvent) => void;
    onFieldChange: (field: keyof PropertyFormData, value: any) => void;
    onAddFeature: () => void;
    onRemoveFeature: (id: string) => void;
    onUpdateFeature: (id: string, description: string) => void;
    onAddArea: () => void;
    onRemoveArea: (id: string) => void;
    onUpdateArea: (id: string, field: string, value: any) => void;
    onAreaImageRemove: (areaId: string, imageId: string) => void;
    onAreaImagesSelect: (areaId: string, imageIds: string[]) => void;
    handleAreaImageUpload: (areaId: string, files: FileList) => Promise<void>;
    onFetchLocationData: () => Promise<void>;
    onGenerateLocationDescription: () => Promise<void>;
    onGenerateMap: () => Promise<void>;
    onRemoveNearbyPlace: (index: number) => void;
    isLoadingLocationData: boolean;
    isGeneratingMap: boolean;
    onFetchCategoryPlaces: (category: string) => Promise<any>;
    onFetchNearbyCities: () => Promise<void>;
    currentStep: number;
    handleStepClick: (step: number) => void;
    setPendingChanges: (value: boolean) => void;
    isSaving?: boolean;
    handleVirtualTourUpdate?: (url: string) => void;
    handleYoutubeUrlUpdate?: (url: string) => void;
    handleFloorplanEmbedScriptUpdate?: (script: string) => void;
  };
}
