
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjvpptmwijiosgdcozep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdnBwdG13aWppb3NnZGNvemVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNDY2MjgsImV4cCI6MjA1NDcyMjYyOH0.-y3EH6GCtlig7d2FGTcSuyAAYtGsKbP4NrKeaMD-OMg";

// Create and export the Supabase client with optimized settings for better startup performance
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false, // Disable checking URL for sign-in tokens (faster initial load)
    },
    global: {
      fetch: (...args) => {
        // Add a longer timeout for fetch requests to avoid quick failures
        return fetch(...args);
      }
    }
  }
);

// Add a simple check to verify the client is working
try {
  console.log("Supabase client initialized");
} catch (e) {
  console.error("Failed to initialize Supabase client", e);
}
